// ***********************/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**
// pulp_common_cells     /**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/***
// *********************/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/****
+incdir+$RTL_ROOT/soc/dip_pulp_common_cells
+incdir+$RTL_ROOT/soc/dip_pulp_common_cells/include
+incdir+$RTL_ROOT/soc/dip_pulp_common_cells/include/common_cells
//- include/common_cells/registers.svh : {is_include_file : true, include_path : include}
//- include/common_cells/assertions.svh : {is_include_file : true, include_path : include}
//$RTL_ROOT/soc/dip_pulp_common_cells/include/common_cells/registers.svh
//$RTL_ROOT/soc/dip_pulp_common_cells/include/common_cells/assertions.svh
$RTL_ROOT/soc/dip_pulp_common_cells/src/binary_to_gray.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cb_filter_pkg.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cc_onehot.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cf_math_pkg.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/clk_int_div.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/credit_counter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/delta_counter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/ecc_pkg.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/edge_propagator_tx.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/exp_backoff.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/fifo_v3.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/gray_to_binary.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/isochronous_4phase_handshake.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/isochronous_spill_register.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/lfsr.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/lfsr_16bit.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/lfsr_8bit.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/multiaddr_decode.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/mv_filter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/onehot_to_bin.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/plru_tree.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/passthrough_stream_fifo.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/popcount.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/rr_arb_tree.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/rstgen_bypass.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/serial_deglitch.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/shift_reg.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/shift_reg_gated.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/spill_register_flushable.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_demux.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_filter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_fork.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_intf.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_join.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_join_dynamic.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_mux.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_throttle.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/sub_per_hash.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/sync.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/sync_wedge.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/unread.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/read.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_reset_ctrlr_pkg.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/addr_decode_dync.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_2phase.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_4phase.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cb_filter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_fifo_2phase.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/counter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/ecc_decode.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/ecc_encode.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/edge_detect.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/lzc.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/max_counter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/rstgen.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/spill_register.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_delay.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_fifo.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_fork_dynamic.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/clk_mux_glitch_free.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/addr_decode.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/addr_decode_napot.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_reset_ctrlr.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_fifo_gray.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/fall_through_register.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/id_queue.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_to_mem.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_arbiter_flushable.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_fifo_optimal_wrap.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_register.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_xbar.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_fifo_gray_clearable.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/cdc_2phase_clearable.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/mem_to_banks_detailed.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_arbiter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/stream_omega_net.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/mem_to_banks.sv

// *************************/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**\**\****/**/**
// pulp_common_cells_test  /**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/****\**\**/**/***
// ***********************/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/******\**\/**/****
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/clock_divider_counter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/clk_div.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/find_first_one.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/generic_LFSR_8bit.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/generic_fifo.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/prioarbiter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/pulp_sync.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/pulp_sync_wedge.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/rrarbiter.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/clock_divider.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/fifo_v2.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/deprecated/fifo_v1.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/edge_propagator_ack.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/edge_propagator.sv
$RTL_ROOT/soc/dip_pulp_common_cells/src/edge_propagator_rx.sv
